version: '3'

services:
  app:
    build: 
      context: ./../	# https://stackoverflow.com/questions/24537340/docker-adding-a-file-from-a-parent-directory
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      actuatoradmin:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@library.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ${PWD}/pgadmin4/servers.json:/pgadmin4/servers.json
    ports:
      - "8081:80"    
    depends_on:
      - postgres

  actuatoradmin:
    build: ./SpringActuatorAdmin
    restart: always
    ports:
      - "8082:8082"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  db-data:
